### ISSUE TITLE
[Feature Request]: Plugin Support

### ISSUE THREAD

**Issue by Mqxx** [Papierkorb2292/MultiScoreboard#1]
Hey, would it be possible that you write a plugin like the server side mod for non modded servers. I would like to use the mod on my purpurmc server.

**Comment by Papierkorb2292** [comment]
I don't have much experience with plugin development, so I'm currently not able to write such a plugin. Furthermore, I'm not sure whether this mod is portable for purpurmc, due to its use of mixins to modify scoreboard data and scoreboard rendering.
If somebody else would like to port it to purpurmc, feel free to reply on this issue and if necessary, I could explain how the mod works and what the plugin would thus need to do.

For now, I can only recommend to switch to fabric or potentially quilt, which I recommend to do anyway when working with commands, since they make less changes to vanilla.
